version: '3'

services:
  app:
    image: ghcr.io/rajkumaar23/playstore-api:main
    restart: always
    volumes:
      - .env:/app/.env
    ports:
      - "5003:5003"
    depends_on:
      - redis
    networks:
      - playstore-api-network

  redis:
    image: redis:latest
    restart: always
    networks:
      - playstore-api-network

networks:
  playstore-api-network:
    driver: bridge
