version: '3'

services:
  app:
    image: ghcr.io/rajkumaar23/api-playstore:main
    restart: always
    volumes:
      - .env:/app/.env
    ports:
      - "5003:5003"
    depends_on:
      - redis
    networks:
      - api-playstore-network

  redis:
    image: redis:latest
    restart: always
    networks:
      - api-playstore-network

networks:
  api-playstore-network:
    driver: bridge
